version: '3.8'

services:
  fika-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - DATABASE_URL=sqlite:///data/fika_bot.db
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: python slack_bot.py
